# Generated by Django 4.2.2 on 2023-09-10 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('IssueBureau', models.CharField(choices=[('MOL', 'MinisterOfLabor'), ('IMB', 'ImmigrationBureau'), ('DOH', 'DepartmentOfHealth'), ('MFA', 'MinisterOfForeignerAffairs'), ('DOA', 'DepartmentOfAgriculture')], default='MOL', max_length=3)),
                ('IssueDate', models.DateField(default=datetime.date.today)),
                ('Text', models.TextField()),
                ('image', models.FileField(upload_to='NewPolicy/')),
            ],
        ),
    ]
